customhost = "database-1.cn0yq6a6wqlo.ap-south-1.rds.amazonaws.com"
customuser = "admin"
custompass = "admin123"
customdb = "employee"
custombucket = "mytestdatastore"
customregion = "ap-south-1"
